// src/knowledge.js — Laien-Wissen: Welche Dokumente? Was bedeuten die Begriffe?

// ─── DOKUMENTEN-GUIDE ───
// Erklärt jedem Laien: Was ist das Dokument? Warum braucht NIS2 es? Was muss rein?
export const DOCUMENT_GUIDE = [
  {
    id: "leitlinie",
    icon: "📜",
    name: "Informationssicherheitsleitlinie",
    kurz: "Das Grundsatzdokument der Chefetage zur IT-Sicherheit",
    laie: "Stell dir das wie ein Versprechen der Geschäftsführung vor: „So ernst nehmen wir IT-Sicherheit in unserem Unternehmen.“ Es ist das oberste Dokument, auf das sich alle anderen Regeln beziehen.",
    warum: "NIS2 verlangt, dass die Geschäftsführung Verantwortung übernimmt. Ohne dieses unterschriebene Dokument gibt es keinen formalen Nachweis dafür.",
    mussRein: [
      "Unterschrift und Datum der Geschäftsführung",
      "Wer ist verantwortlich (der ISB)",
      "Für wen gilt es (alle Mitarbeiter)",
      "Wann wird es überprüft (z.B. jährlich)",
    ],
    tipp: "Eine generische Vorlage aus dem Internet reicht NICHT. Es muss euer Unternehmen nennen und unterschrieben sein.",
    nis2: "BSI ISMS.1.A3 · § 38 BSIG",
  },
  {
    id: "risiko",
    icon: "⚠️",
    name: "Risikoanalyse",
    kurz: "Die Übersicht: Was kann schiefgehen und wie schlimm wäre es?",
    laie: "Hier listet ihr auf, welche Gefahren es für eure IT gibt (z.B. Hackerangriff, Stromausfall, Datenverlust) und bewertet, wie wahrscheinlich und wie schlimm jede Gefahr ist. Danach entscheidet ihr, was ihr dagegen tut.",
    warum: "NIS2 verlangt, dass ihr eure Risiken systematisch kennt. Man kann sich nur schützen, wenn man weiß wovor.",
    mussRein: [
      "Liste eurer wichtigen IT-Systeme (kommt aus dem Asset-Inventar)",
      "Welche Gefahren bedrohen sie",
      "Wie wahrscheinlich und wie teuer wäre der Schaden",
      "Was tut ihr dagegen — und wer ist zuständig",
    ],
    tipp: "Ohne ein Asset-Inventar (siehe unten) ist eine Risikoanalyse unvollständig. Erst die Systeme erfassen, dann die Risiken.",
    nis2: "BSI 200-3 · § 30 Abs. 2 Nr. 1 BSIG",
  },
  {
    id: "asset",
    icon: "🗂️",
    name: "Asset-Inventar",
    kurz: "Die vollständige Liste eurer IT — vom Server bis zur Cloud",
    laie: "Eine Inventarliste aller IT-Gegenstände: Server, Laptops, Software, Cloud-Dienste, Datenbanken. Für jeden Eintrag: Wie wichtig ist er? Wer kümmert sich darum? Hängt etwas Kritisches davon ab?",
    warum: "Ihr könnt nichts schützen, was ihr nicht kennt. Das Asset-Inventar ist die Grundlage für fast alles andere.",
    mussRein: [
      "Alle Systeme: Hardware, Software, Cloud, ggf. Produktionsanlagen",
      "Wie kritisch ist jedes System für den Betrieb",
      "Wer ist verantwortlich (Owner)",
      "Wann zuletzt aktualisiert",
    ],
    tipp: "Eine reine Hardware-Liste reicht nicht. Cloud-Dienste (Microsoft 365, etc.) und kritische Software gehören dazu.",
    nis2: "BSI ORP.4 · § 30 Abs. 2 BSIG",
  },
  {
    id: "backup",
    icon: "💾",
    name: "Backup- & Notfallkonzept",
    kurz: "Der Plan: Wie kommt ihr nach einem Ausfall wieder ans Laufen?",
    laie: "Beschreibt, wie ihr eure Daten sichert und wie ihr nach einem Notfall (z.B. Ransomware, Serverausfall) den Betrieb wiederherstellt. Wichtig: Ihr müsst auch beweisen, dass die Wiederherstellung wirklich funktioniert — nicht nur, dass ihr Backups macht.",
    warum: "Ein Hackerangriff oder Ausfall darf euch nicht lahmlegen. NIS2 verlangt einen erprobten Wiederanlaufplan.",
    mussRein: [
      "RTO: Wie schnell muss ein System wieder laufen?",
      "RPO: Wie viele Daten dürft ihr maximal verlieren?",
      "Protokolle von echten Wiederherstellungs-Tests",
      "Schutz gegen Ransomware (z.B. nicht-überschreibbare Backups)",
    ],
    tipp: "Der häufigste Fehler: „Wir machen Backups“ ohne je getestet zu haben, ob die Wiederherstellung klappt. Test-Protokolle sind Pflicht.",
    nis2: "BSI 200-4 · § 30 Abs. 2 Nr. 3 BSIG",
  },
  {
    id: "incident",
    icon: "🚨",
    name: "Incident-Response-Plan",
    kurz: "Die Anleitung: Was tun, wenn es zum Sicherheitsvorfall kommt?",
    laie: "Ein Notfall-Drehbuch für Sicherheitsvorfälle. Wer wird informiert? Wer entscheidet? Und ganz wichtig bei NIS2: Schwere Vorfälle müssen innerhalb von 24 Stunden an die Behörde (BSI) gemeldet werden.",
    warum: "Im Ernstfall zählt jede Minute. NIS2 schreibt feste Meldefristen vor — die müsst ihr vorbereitet haben.",
    mussRein: [
      "Was gilt überhaupt als Sicherheitsvorfall",
      "Meldekette: Wer informiert wen",
      "Die 24-Stunden-Frühwarnung und 72-Stunden-Meldung ans BSI",
      "Kontaktdaten (intern und BSI)",
    ],
    tipp: "Die 24h/72h-Fristen ans BSI sind das Herzstück. Ein Plan ohne diese Fristen erfüllt NIS2 nicht.",
    nis2: "BSI DER.2.1 · § 32 BSIG",
  },
  {
    id: "lieferanten",
    icon: "🔗",
    name: "Lieferantenübersicht",
    kurz: "Wer hat Zugriff auf eure Systeme — und wie sicher sind die?",
    laie: "Eine Liste aller externen Dienstleister, die Zugang zu euren Systemen oder Daten haben (z.B. IT-Dienstleister, Cloud-Anbieter, Wartungsfirmen). Für jeden: Wie kritisch ist er und welche Sicherheitsnachweise hat er?",
    warum: "Ein Angreifer nutzt oft den schwächsten Partner als Einfallstor. NIS2 verlangt, dass ihr eure Lieferkette absichert.",
    mussRein: [
      "Alle Dienstleister mit Systemzugang",
      "Wie kritisch ist jeder für euch",
      "Sicherheitsanforderungen in den Verträgen",
      "Nachweise der Lieferanten (z.B. ISO 27001)",
    ],
    tipp: "Eine reine Adressliste reicht nicht. Es geht um die Sicherheitsbewertung jedes Partners.",
    nis2: "§ 30 Abs. 2 Nr. 4 BSIG",
  },
  {
    id: "schulung",
    icon: "🎓",
    name: "Schulungsnachweise",
    kurz: "Beweis, dass eure Mitarbeiter geschult werden",
    laie: "Belege dafür, dass eure Mitarbeiter regelmäßig in IT-Sicherheit geschult werden — z.B. Teilnahmelisten, Schulungspläne, Ergebnisse von Phishing-Tests.",
    warum: "Die meisten Angriffe zielen auf Menschen, nicht auf Technik. NIS2 verlangt deshalb regelmäßige Sensibilisierung.",
    mussRein: [
      "Schulungsplan für das Jahr",
      "Teilnahmenachweise der Mitarbeiter",
      "Auch die Geschäftsführung muss geschult werden",
      "Idealerweise: Phishing-Simulationen mit Auswertung",
    ],
    tipp: "Auch die Chefetage muss nachweislich geschult sein — das verlangt § 38 BSIG (Geschäftsleitungspflichten) ausdrücklich.",
    nis2: "BSI ORP.3 · § 30 Abs. 2 Nr. 6, § 38 BSIG",
  },
  {
    id: "iam",
    icon: "🔑",
    name: "Berechtigungskonzept (IAM)",
    kurz: "Wer darf auf was zugreifen — und wer kontrolliert das?",
    laie: "Hier wird geregelt, welcher Mitarbeiter auf welche Systeme und Daten zugreifen darf. Das Prinzip: Jeder bekommt nur die Rechte, die er für seine Arbeit wirklich braucht — nicht mehr. Besonders Admin-Konten mit weitreichenden Rechten müssen streng kontrolliert werden.",
    warum: "NIS2 verlangt kontrollierten Zugriff. Wenn jeder überall hinkommt, kann ein einziges gestohlenes Passwort das ganze Unternehmen gefährden.",
    mussRein: [
      "Rollenmodell: welche Rolle darf was",
      "Regelung für Admin-/Sonderkonten",
      "Prozess für Ein- und Austritt von Mitarbeitern",
      "Regelmäßige Überprüfung der Berechtigungen",
    ],
    tipp: "Achten Sie besonders auf verwaiste Konten von ausgeschiedenen Mitarbeitern — die sind ein häufiges Einfallstor.",
    nis2: "BSI ORP.4 · § 30 Abs. 2 BSIG",
  },
  {
    id: "mfa",
    icon: "📱",
    name: "MFA- / Authentisierungskonzept",
    kurz: "Login mit zwei Schritten statt nur Passwort",
    laie: "MFA (Multi-Faktor-Authentifizierung) bedeutet: Zum Einloggen reicht nicht das Passwort allein, sondern es braucht einen zweiten Faktor — z.B. einen Code aufs Handy. Das schützt selbst dann, wenn ein Passwort gestohlen wird. Dieses Konzept legt fest, wo MFA Pflicht ist.",
    warum: "NIS2 nennt gesicherte Authentisierung ausdrücklich. Gerade für Fernzugriffe und kritische Systeme ist MFA praktisch unverzichtbar.",
    mussRein: [
      "Für welche Systeme gilt MFA verpflichtend",
      "Welche Verfahren werden eingesetzt (App, Hardware-Token)",
      "Regelung für Fernzugriff / VPN",
      "Nachweis, dass MFA aktiv ist (nicht nur geplant)",
    ],
    tipp: "Ein Konzept allein reicht nicht — entscheidend ist der Nachweis, dass MFA für kritische Systeme tatsächlich aktiviert ist.",
    nis2: "BSI ORP.4.A23 · § 30 Abs. 2 BSIG",
  },
  {
    id: "patch",
    icon: "🩹",
    name: "Patch- & Schwachstellenmanagement",
    kurz: "Sicherheitslücken finden und schließen, bevor jemand sie ausnutzt",
    laie: "Software hat immer wieder Sicherheitslücken. Dieses Dokument regelt, wie Sie diese Lücken erkennen (z.B. durch Scans) und wie schnell Sie Updates (Patches) einspielen. Je kritischer das System, desto schneller muss gehandelt werden.",
    warum: "NIS2 verlangt, dass Schwachstellen systematisch behandelt werden. Ungepatchte Systeme sind eine der häufigsten Ursachen für erfolgreiche Angriffe.",
    mussRein: [
      "Prozess, wie Updates eingespielt werden",
      "Fristen je nach Kritikalität (z.B. kritische Lücken in 7 Tagen)",
      "Schwachstellen-Register oder Scan-Ergebnisse",
      "Verantwortliche Person",
    ],
    tipp: "Wichtig ist ein nachvollziehbarer Prozess mit Fristen — nicht nur 'wir machen Updates, wenn wir Zeit haben'.",
    nis2: "BSI OPS.1.1.3 · § 30 Abs. 2 BSIG",
  },
  {
    id: "logging",
    icon: "📊",
    name: "Logging- & Monitoring-Konzept",
    kurz: "Aufzeichnen, was in den Systemen passiert — um Angriffe zu erkennen",
    laie: "Logging heißt: Die Systeme schreiben mit, wer wann was gemacht hat. Monitoring heißt: Diese Aufzeichnungen werden überwacht, damit verdächtige Aktivitäten auffallen. Ohne das merkt man einen Angriff oft erst, wenn es zu spät ist.",
    warum: "NIS2 verlangt, dass Sicherheitsvorfälle erkannt werden können. Und für die 24h/72h-Meldepflicht müssen Sie überhaupt wissen, dass und was passiert ist.",
    mussRein: [
      "Welche Systeme protokollieren (Logs)",
      "Wie lange werden Logs aufbewahrt",
      "Wer wertet sie aus / wird alarmiert",
      "Idealerweise: zentrale Sammlung (SIEM)",
    ],
    tipp: "Logs zu sammeln reicht nicht — jemand oder ein System muss sie auch auswerten, sonst sind sie nutzlos.",
    nis2: "BSI DER.1 · § 30 Abs. 2 BSIG",
  },
  {
    id: "krypto",
    icon: "🔐",
    name: "Kryptografie- / Verschlüsselungskonzept",
    kurz: "Wo und wie werden Daten verschlüsselt?",
    laie: "Verschlüsselung macht Daten für Unbefugte unlesbar. Dieses Konzept legt fest, wo verschlüsselt wird — z.B. bei der Datenübertragung (HTTPS, VPN), auf Laptops (Festplattenverschlüsselung) und in Backups. So sind Daten auch dann geschützt, wenn ein Gerät verloren geht.",
    warum: "NIS2 nennt Kryptografie ausdrücklich als Maßnahme. Verschlüsselung schützt Vertraulichkeit selbst dann, wenn andere Schutzmaßnahmen versagen.",
    mussRein: [
      "Wo wird verschlüsselt (Transport, Speicher, Backups)",
      "Welche Verfahren / Standards",
      "Wie werden Schlüssel verwaltet",
      "Regelung für mobile Geräte (Laptops, Handys)",
    ],
    tipp: "Festplattenverschlüsselung auf Laptops ist ein schneller, wirkungsvoller erster Schritt — oft mit Bordmitteln möglich.",
    nis2: "BSI CON.1 · § 30 Abs. 2 BSIG",
  },
];

// ─── GLOSSAR ───
// Jeder Fachbegriff in einem Satz Klartext
export const GLOSSARY = {
  "NIS2": "Eine EU-Richtlinie für Cybersicherheit. In Deutschland ist sie über das novellierte BSI-Gesetz (BSIG) umgesetzt, das seit dem 6. Dezember 2025 gilt. Es verpflichtet viele Unternehmen, ihre IT besser zu schützen.",
  "ISMS": "Informationssicherheits-Managementsystem. Klingt kompliziert, heißt einfach: ein geordnetes System, mit dem ein Unternehmen seine IT-Sicherheit organisiert und nachweisbar macht.",
  "ISB": "Informationssicherheitsbeauftragter. Die Person im Unternehmen, die für IT-Sicherheit zuständig ist — eine Art Sicherheits-Verantwortlicher.",
  "BSI": "Bundesamt für Sicherheit in der Informationstechnik. Die deutsche Behörde für Cybersicherheit. Bei NIS2 ist sie die Meldestelle für Vorfälle.",
  "KRITIS": "Kritische Infrastrukturen — Unternehmen, deren Ausfall die Gesellschaft gefährden würde, z.B. Strom-, Wasser- oder Krankenhausversorgung.",
  "RTO": "Recovery Time Objective. Auf Deutsch: Wie schnell muss ein System nach einem Ausfall wieder laufen? (z.B. „innerhalb von 4 Stunden“)",
  "RPO": "Recovery Point Objective. Auf Deutsch: Wie viele Daten dürft ihr im Notfall maximal verlieren? (z.B. „maximal die letzte Stunde“)",
  "Asset": "Ein IT-Gegenstand oder -Wert: Server, Laptop, Software, Cloud-Dienst, Datenbank. Alles, was zur IT gehört und schützenswert ist.",
  "Gap-Analyse": "Ein Soll-Ist-Vergleich. Sie zeigt die Lücke zwischen dem, was NIS2 verlangt (Soll), und dem, was ihr schon habt (Ist).",
  "Nachweis": "Auch „Evidence“ genannt. Ein Beleg dafür, dass eine Sicherheitsmaßnahme wirklich umgesetzt ist — nicht nur behauptet wird.",
  "Evidence Score": "Eine Bewertung von 0 bis 100, wie gut ein Dokument als Nachweis taugt. Niedrig heißt: Das Dokument hält einer Prüfung nicht stand.",
  "BCM": "Business Continuity Management. Das Notfallmanagement für den Geschäftsbetrieb — der Plan, wie das Unternehmen nach einem Ausfall weiterarbeitet.",
  "BIA": "Business Impact Analyse. Die Untersuchung, welche Geschäftsprozesse am wichtigsten sind und wie teuer ihr Ausfall wäre.",
  "MFA": "Multi-Faktor-Authentifizierung. Login mit zwei Schritten statt nur Passwort — z.B. Passwort plus Code aufs Handy. Schützt vor Passwortdiebstahl.",
  "VVT": "Verzeichnis von Verarbeitungstätigkeiten. Eine Übersicht aller Stellen, an denen personenbezogene Daten verarbeitet werden (Pflicht aus der DSGVO).",
  "Besonders wichtige Einrichtung": "Die strengere NIS2-Kategorie. Trifft auf größere Unternehmen in besonders kritischen Sektoren zu — mit höheren Pflichten und Bußgeldern.",
  "Wichtige Einrichtung": "Die zweite NIS2-Kategorie. Etwas weniger streng als „besonders wichtig“, aber ebenfalls voll von NIS2 betroffen.",
};

// ─── FRAGEN pro Dokumenttyp (wenn Nutzer kein Dokument hat) ───
export const DOC_QUESTIONS = {
  "Informationssicherheitsleitlinie": [
    { id: "verantwortlich", frage: "Wer ist bei Ihnen für IT-Sicherheit verantwortlich?", placeholder: "z.B. IT-Leiter Herr Müller, oder noch niemand" },
    { id: "ziele", frage: "Was sind Ihre wichtigsten Sicherheitsziele?", placeholder: "z.B. Schutz von Kundendaten, Verfügbarkeit der Produktion" },
    { id: "freigabe", frage: "Hat die Geschäftsführung dem Thema schon formal zugestimmt?", placeholder: "z.B. ja mündlich, noch nichts schriftlich" },
  ],
  "Incident-Response-Plan": [
    { id: "meldeweg", frage: "An wen wird aktuell ein IT-Problem gemeldet?", placeholder: "z.B. an die IT-Abteilung per Mail" },
    { id: "verantwortlich", frage: "Wer entscheidet im Notfall?", placeholder: "z.B. IT-Leiter, im Urlaub niemand" },
    { id: "extern", frage: "Haben Sie einen externen IT-Dienstleister für Notfälle?", placeholder: "z.B. ja, Firma XY mit 4h-Reaktionszeit" },
  ],
  "Risikoanalyse": [
    { id: "systeme", frage: "Was sind Ihre wichtigsten IT-Systeme?", placeholder: "z.B. ERP, Produktionssteuerung, Mailserver" },
    { id: "gefahren", frage: "Wovor haben Sie am meisten Sorge?", placeholder: "z.B. Ransomware, Ausfall der Produktion" },
    { id: "massnahmen", frage: "Welche Schutzmaßnahmen haben Sie schon?", placeholder: "z.B. Firewall, Virenschutz, Backups" },
  ],
  "Asset-Inventar": [
    { id: "systeme", frage: "Welche IT-Systeme setzen Sie ein?", placeholder: "z.B. 20 Laptops, 3 Server, Microsoft 365" },
    { id: "cloud", frage: "Welche Cloud-Dienste nutzen Sie?", placeholder: "z.B. Microsoft 365, Datev, Salesforce" },
    { id: "kritisch", frage: "Welches System wäre am schlimmsten bei Ausfall?", placeholder: "z.B. die Produktionssteuerung" },
  ],
  "Backup- & Notfallkonzept": [
    { id: "backup", frage: "Wie sichern Sie aktuell Ihre Daten?", placeholder: "z.B. tägliches Backup auf NAS" },
    { id: "test", frage: "Haben Sie schon mal eine Wiederherstellung getestet?", placeholder: "z.B. nein, noch nie" },
    { id: "rto", frage: "Wie lange dürfte ein wichtiges System maximal ausfallen?", placeholder: "z.B. maximal 4 Stunden" },
  ],
  "Lieferantenübersicht": [
    { id: "dienstleister", frage: "Welche externen Dienstleister haben Zugriff auf Ihre Systeme?", placeholder: "z.B. IT-Firma, Cloud-Anbieter, Wartung" },
    { id: "kritisch", frage: "Welcher davon ist am wichtigsten für Sie?", placeholder: "z.B. unser IT-Dienstleister" },
    { id: "vertrag", frage: "Gibt es Sicherheitsvereinbarungen in den Verträgen?", placeholder: "z.B. AVV vorhanden, sonst nichts" },
  ],
  "Schulungsnachweise": [
    { id: "schulung", frage: "Werden Mitarbeiter aktuell geschult?", placeholder: "z.B. nein, oder einmalig beim Eintritt" },
    { id: "phishing", frage: "Gab es schon Phishing-Tests?", placeholder: "z.B. nein" },
    { id: "management", frage: "Wurde die Geschäftsführung geschult?", placeholder: "z.B. nein" },
  ],
  "Berechtigungskonzept (IAM)": [
    { id: "rollen", frage: "Wie regeln Sie aktuell, wer auf was zugreifen darf?", placeholder: "z.B. jeder hat lokale Adminrechte, oder Rollen in Microsoft 365" },
    { id: "admin", frage: "Wie viele Personen haben Admin-Rechte?", placeholder: "z.B. 3 Personen, oder unklar" },
    { id: "austritt", frage: "Was passiert mit Konten, wenn jemand das Unternehmen verlässt?", placeholder: "z.B. wird manuell gelöscht, oft vergessen" },
  ],
  "MFA- / Authentisierungskonzept": [
    { id: "wo", frage: "Wo nutzen Sie heute schon Zwei-Faktor-Login (MFA)?", placeholder: "z.B. nur bei Microsoft 365, sonst nirgends" },
    { id: "fern", frage: "Wie sichern Sie Fernzugriffe / VPN ab?", placeholder: "z.B. nur Passwort, oder mit MFA" },
    { id: "kritisch", frage: "Welche kritischen Systeme haben noch KEIN MFA?", placeholder: "z.B. Server-Logins, ERP" },
  ],
  "Patch- & Schwachstellenmanagement": [
    { id: "updates", frage: "Wie spielen Sie aktuell Updates ein?", placeholder: "z.B. automatisch bei Windows, Server manuell" },
    { id: "fristen", frage: "Gibt es Fristen für kritische Sicherheitsupdates?", placeholder: "z.B. nein, wird gemacht wenn Zeit ist" },
    { id: "scan", frage: "Prüfen Sie Systeme auf Schwachstellen (Scans)?", placeholder: "z.B. nein, oder einmal jährlich" },
  ],
  "Logging- & Monitoring-Konzept": [
    { id: "logs", frage: "Welche Systeme protokollieren bei Ihnen (Logs)?", placeholder: "z.B. Firewall und Server, aber niemand schaut rein" },
    { id: "auswertung", frage: "Wertet jemand diese Logs aus oder wird alarmiert?", placeholder: "z.B. nein, nur im Problemfall" },
    { id: "aufbewahrung", frage: "Wie lange werden Logs aufbewahrt?", placeholder: "z.B. unbekannt, oder 30 Tage" },
  ],
  "Kryptografie- / Verschlüsselungskonzept": [
    { id: "transport", frage: "Wie sichern Sie die Datenübertragung ab?", placeholder: "z.B. HTTPS und VPN, sonst nichts" },
    { id: "geraete", frage: "Sind Laptops und mobile Geräte verschlüsselt?", placeholder: "z.B. nein, oder nur teilweise" },
    { id: "backups", frage: "Sind Ihre Backups verschlüsselt?", placeholder: "z.B. unbekannt" },
  ],
};
